name: Hello Workflow
on:
  push:
    branches:
      - main
      
env:
  name: 'Giorgio'
  
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
          
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
    - name: aaaa
      run: |
        echo "Hello World!"
        echo "Hi ${name} !"
    
          
